services:
  tgbot.nginx:
    container_name: tgbot.nginx
    networks:
      - tgbot-net
    ports:
      - "${NGINX_PORT}:80"
    image: nginx:stable-alpine
    volumes:
      - ./src:/app
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - tgbot.php
    restart: unless-stopped

  tgbot.php:
    container_name: tgbot.php
    networks:
      - tgbot-net
    working_dir: /app
    environment:
      - TZ=Europe/Moscow
    build:
      dockerfile: docker/php/Dockerfile
      context: ./
    volumes:
      - ./src/:/app
    depends_on:
      - tgbot.db
      - tgbot.memcached
    restart: unless-stopped

  tgbot.db:
    container_name: tgbot.db
    networks:
      - tgbot-net
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    volumes:
      - tgbot.db.data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  tgbot.memcached:
    container_name: tgbot.memcached
    image: memcached:latest
    restart: unless-stopped

volumes:
  tgbot.db.data:

networks:
  tgbot-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
